services:
  saml-idp:
    image: ghcr.io/alshawwaf/saml_idp_simulator:latest
    build:
      context: https://github.com/alshawwaf/SAML_IDP_Simulator.git
      dockerfile: Dockerfile
    container_name: saml-idp-simulator
    restart: unless-stopped
    environment:
      - ADMIN_USERNAME=admin@cpdemo.ca
      - ADMIN_PASSWORD=Cpwins!1@2026
      - SECRET_KEY=Super-very-secret-key-cpdemo-2026
      - IDP_HOST=0.0.0.0
      - IDP_PORT=5000
      - ENABLE_SSL=false
      - FLASK_DEBUG=1
      - CERT_PATH=/app/app/certs/idp-cert.pem
      - KEY_PATH=/app/app/certs/idp-key.pem
    volumes:
      - saml_idp_data:/app/data
      - saml_idp_certs:/app/app/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saml-idp.rule=Host(`idp.cpdemo.ca`)"
      - "traefik.http.routers.saml-idp.entrypoints=websecure"
      - "traefik.http.routers.saml-idp.tls.certresolver=letsencrypt"
      - "traefik.http.services.saml-idp.loadbalancer.server.port=5000"
    networks:
      - dokploy-network

volumes:
  saml_idp_data:
  saml_idp_certs:

networks:
  dokploy-network:
    external: true
