###############################################################################
# Multi-Service Stack
# - n8n (workflow automation)
# - PostgreSQL (n8n backend)
# - Ollama (local LLMs) CPU/GPU
# - Langflow (AI flow builder)
# - Open-WebUI (AI chat interface)
# - Flowise (LLM orchestration UI)
# - Qdrant (vector database)
###############################################################################

###############################################################################
# Networks
###############################################################################
networks:
  demo:
  dokploy-network:
    external: true
    ###############################################################################
    # Volumes
    ###############################################################################
volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:
  open-webui:
  flowise:
  langflow:
  vllm_storage:

    ###############################################################################
    # Common Service Definitions (Anchors)
    ###############################################################################

    # ──────────────── n8n Base ────────────────
x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: [ "demo" ]
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=admin
    - DB_POSTGRESDB_PASSWORD=Cpwins!1
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    # IMPORTANT for container-to-container curl
    - N8N_SECURE_COOKIE=false
    - N8N_ENCRYPTION_KEY=long_random_encryption_key_here
    - N8N_USER_MANAGEMENT_JWT_SECRET=supersecretjwtkey
    # we will ALSO call /rest/owner/setup in the provisioner with these:
    - N8N_USER_MANAGEMENT_EMAIL=admin@{{DOMAIN}}
    - N8N_USER_MANAGEMENT_FIRST_NAME=Admin
    - N8N_USER_MANAGEMENT_LAST_NAME=Agentic
    - N8N_USER_MANAGEMENT_PASSWORD=Cpwins!1@2026
    - N8N_USER_MANAGEMENT_DISABLED=false
    # basic auth (MUST match provisioner)
    - N8N_BASIC_AUTH_ACTIVE=true
    - N8N_BASIC_AUTH_USER=admin
    - N8N_BASIC_AUTH_PASSWORD=Cpwins!1@2026
    - WEBHOOK_URL=https://n8n.{{DOMAIN}}/
    - N8N_EDITOR_BASE_URL=https://n8n.{{DOMAIN}}/
    - N8N_PUSH_BACKEND=websocket
    # allow community packages
    - N8N_COMMUNITY_PACKAGES_ENABLED=true
    - N8N_UNVERIFIED_PACKAGES_ENABLED=true
    - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true

# ──────────────── Ollama Base ────────────────

x-ollama: &service-ollama
  image: ollama/ollama:latest
  networks: [ "demo" ]
  restart: unless-stopped
  ports:
    - "11434:11434"
  volumes:
    - ollama_storage:/root/.ollama
  # ensure the daemon is actually ready before dependents run
  healthcheck:
    test: [ "CMD-SHELL", "OLLAMA_HOST=http://127.0.0.1:11434 ollama list >/dev/null 2>&1" ]
    interval: 5s
    timeout: 5s
    retries: 20

# ──────────────── Ollama Model Puller ────────────────
x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: [ "demo" ]
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  command:
    - "-lc"
    - |
      set -e
      echo "Waiting for Ollama @ ollama ..."
      # loop until the server responds
      until OLLAMA_HOST="ollama" ollama list >/dev/null 2>&1; do
        echo "  Ollama not ready yet..."
        sleep 3
      done
      echo "Ollama is ready. Pulling models…"
      OLLAMA_HOST="ollama" ollama pull huihui_ai/qwen3-abliterated
      OLLAMA_HOST="ollama" ollama pull mannix/llama3.1-8b-abliterated
      # OLLAMA_HOST="ollama" ollama pull huihui_ai/gpt-oss-abliterated
      OLLAMA_HOST="ollama" ollama pull gpt-oss:20b-cloud
      OLLAMA_HOST="ollama" ollama pull kimi-k2-thinking:cloud
      OLLAMA_HOST="ollama" ollama pull minimax-m2:cloud
      echo "LLM Models pulled successfully!!!"
      echo "Cloud LLMs require Ollama signin to link this environment o your account for billing (free @Nov2025)"
      ollama signin

###############################################################################
# Services
###############################################################################
services:
  # ──────────────── PostgreSQL ────────────────
  postgres:
    env_file:
      - .env
    image: postgres:16-alpine
    container_name: postgres
    networks: [ "demo" ]
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Cpwins!1
      - POSTGRES_DB=n8n
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U admin -d n8n" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # ──────────────── Ollama CPU/GPU ────────────────
  ollama-cpu:
    env_file:
      - .env
    profiles: [ "cpu" ]
    image: ollama/ollama:latest
    container_name: ollama-cpu
    networks: [ "demo" ]
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama-cpu:11434
      - OLLAMA_KEEP_ALIVE=-1
    healthcheck:
      # simple: check that the daemon responds
      test: [ "CMD-SHELL", "OLLAMA_HOST=http://127.0.0.1:11434 ollama list >/dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 20

  ollama-gpu:
    env_file:
      - .env
    profiles: [ "gpu-nvidia" ]
    <<: *service-ollama
    container_name: ollama-gpu
    environment:
      - OLLAMA_HOST=http://ollama-gpu:11434
      - OLLAMA_KEEP_ALIVE=-1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  # ──────────────── Ollama Model Pullers ────────────────
  ollama-pull-models-cpu:
    env_file:
      - .env
    profiles: [ "cpu" ]
    image: ollama/ollama:latest
    container_name: ollama-pull-models-cpu
    networks: [ "demo" ]
    volumes:
      - ollama_storage:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama-cpu:11434
    depends_on:
      # let it start, the script will wait in a loop
      - ollama-cpu
    entrypoint: /bin/sh
    command:
      - -lc
      - |
        echo ">> Waiting for Ollama at $ollama ..."
        # loop until Ollama answers
        until OLLAMA_HOST="$ollama" ollama list >/dev/null 2>&1; do
          echo "  ...still waiting for Ollama ($ollama)"
          sleep 3
        done
        echo "Ollama is up. Pulling models..."
        OLLAMA_HOST="$ollama" ollama pull gpt-oss:20b-cloud
        OLLAMA_HOST="$ollama" ollama pull mistral-nemo:latest
        echo "All models pulled!!!"
        # keep the container alive so logs stay visible
        tail -f /dev/null

  ollama-pull-models-gpu:
    env_file:
      - .env
    profiles: [ "gpu-nvidia" ]
    <<: *init-ollama
    container_name: ollama-pull-models-gpu
    environment:
      - OLLAMA_HOST=http://ollama-gpu:11434
    depends_on:
      ollama-gpu:
        condition: service_healthy

  # ──────────────── n8n ────────────────
  n8n:
    env_file:
      - .env
    <<: *service-n8n
    container_name: n8n
    build:
      context: /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/docker/n8n
      dockerfile: Dockerfile
    image: custom-mcp-n8n:custom
    restart: unless-stopped
    networks:
      - demo
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/n8n/backup:/backup
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/n8n/shared:/data/shared
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/n8n/custom-nodes:/home/node/.n8n/custom
    depends_on:
      postgres:
        condition: service_healthy

  # ──────────────── n8n PROVISIONER (owner + login + MCP install) ────────────────
  n8n-provision:
    env_file:
      - .env
    image: curlimages/curl:8.9.1
    container_name: n8n-provision
    networks: [ "demo" ]
    depends_on:
      - n8n
    volumes:
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/scripts:/scripts:ro
    environment:
      # n8n from inside the network
      - N8N_URL=http://n8n:5678
      # owner info (must match what you want in n8n)
      - N8N_ADMIN_EMAIL=admin@{{DOMAIN}}
      - N8N_ADMIN_FIRST_NAME=Admin
      - N8N_ADMIN_LAST_NAME=Agentic
      - N8N_ADMIN_PASSWORD=Cpwins!1@2026
      # package to install
      - N8N_COMMUNITY_PACKAGE=n8n-nodes-mcp
      # must match n8n basic auth above
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Cpwins!1@2026
    command: [ "sh", "/scripts/n8n-provision.sh" ]
    restart: "no"

  # ──────────────── n8n Import Utility ────────────────
  n8n-import:
    env_file:
      - .env
    image: n8nio/n8n:latest
    container_name: n8n-import
    networks: [ "demo" ]
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        echo "Waiting for Postgres..."
        until nc -z -w 3 postgres 5432; do
          echo "Postgres not ready, waiting..."
          sleep 3
        done

        echo "Waiting for n8n..."
        until nc -z -w 3 n8n 5678; do
          echo "n8n not ready, waiting..."
          sleep 5
        done

        echo "Importing n8n credentials & workflows..."
        n8n import:credentials --separate --input=/backup/credentials_public && \
        n8n import:workflow --separate --input=/backup/workflows

        echo "N8N Import completed!!!"

    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=admin
      - DB_POSTGRESDB_PASSWORD=Cpwins!1
      - DB_POSTGRESDB_DATABASE=n8n
      - N8N_ENCRYPTION_KEY=long_random_encryption_key_here
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Cpwins!1@2026
      - N8N_USER_MANAGEMENT_DISABLED=false
    volumes:
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/n8n/backup:/backup
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/n8n/custom-nodes:/home/node/.n8n/custom
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_started
      n8n:
        condition: service_started
      n8n-provision:
        condition: service_completed_successfully
    restart: "no"

  # ──────────────── Flowise ────────────────
  flowise:
    env_file:
      - .env
    profiles: [ "true" ]
    image: flowiseai/flowise
    container_name: flowise
    networks: [ "demo" ]
    restart: unless-stopped
    environment:
      - PORT=3020
    ports:
      - "3020:3020"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/flowise_data:/root/.flowise
    entrypoint: /bin/sh -c "sleep 5; flowise start"

  # ──────────────── Open WebUI ────────────────
  open-webui:
    env_file:
      - .env
    profiles: [ "cpu" ]
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    networks: [ "demo", "dokploy-network" ]
    restart: unless-stopped
    ports:
      - "8090:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/open-webui/pipes/n8n_pipe.py:/app/backend/data/pipes/n8n_pipe.py:ro

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`chat.cpdemo.ca`)"
      - "traefik.http.routers.open-webui.entrypoints=websecure"
      - "traefik.http.routers.open-webui.tls.certresolver=letsencrypt"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
      - "traefik.docker.network=dokploy-network"

    depends_on:
      - ollama-pull-models-cpu

  # ──────────────── Qdrant ────────────────
  qdrant:
    env_file:
      - .env
    image: qdrant/qdrant
    container_name: qdrant
    networks: [ "demo" ]
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/quadrant/backup:/backup

  # ──────────────── Langflow ────────────────
  langflow:
    env_file:
      - .env
    profiles: [ "true" ]
    image: langflowai/langflow:latest
    container_name: langflow
    networks: [ "demo" ]
    restart: unless-stopped
    ports:
      - "7860:7860"
    volumes:
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/langflow/flows:/app/flows
    depends_on:
      - ollama-pull-models-cpu

  # ─────────── Documentation MCP over HTTP ───────────
  mcp-documentation:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: mcp-documentation
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/mcp-documentation" ]
    environment:
      - CLIENT_ID=e650383e3cc7483fa39d098cd2a7b699
      - SECRET_KEY=b2d57cbc56fd414da0489052cdef49c2
      - REGION=EU
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3000"

    ports:
      - "7300:3000"
    restart: unless-stopped

  mcp-https-inspection:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: mcp-https-inspection
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/mcp-https-inspection" ]
    environment:
      - MANAGEMENT_HOST=
      - API_KEY=
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3001"
    ports:
      - "7301:3001"
    restart: unless-stopped

  mcp-quantum-management:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: mcp-quantum-management
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/mcp-quantum-management" ]
    environment:
      - MANAGEMENT_HOST=
      - API_KEY=
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3002"
    ports:
      - "7302:3002"
    restart: unless-stopped

  mcp-management-logs:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: mcp-management-logs
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/mcp-management-logs" ]
    environment:
      - MANAGEMENT_HOST=
      - API_KEY=
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3003"
    ports:
      - "7303:3003"
    restart: unless-stopped

  threat-emulation-mcp:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: threat-emulation-mcp
    networks: [ "demo" ]
    volumes:
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/n8n/shared:/data/shared
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/threat-emulation-mcp" ]
    environment:
      - API_KEY=TE_API_KEY_176159050768979caf55776b947438cc9cae947f
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3004"
    ports:
      - "7304:3004"
    restart: unless-stopped

  threat-prevention-mcp:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: threat-prevention-mcp
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/threat-prevention-mcp" ]
    environment:
      - MANAGEMENT_HOST=
      - API_KEY=
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3005"
    ports:
      - "7305:3005"
    restart: unless-stopped

  spark-management-mcp:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: spark-management-mcp
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/spark-management-mcp" ]
    environment:
      - CLIENT_ID=a6a077cb83a34adfa1e1334bf7e19532
      - SECRET_KEY=a4d87e97b05441bb9d8acace20902234
      - REGION=US
      - INFINITY_PORTAL_URL=https://cloudinfra-gw-us.portal.checkpoint.com/auth/external
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3006"
    ports:
      - "7306:3006"
    restart: unless-stopped

  reputation-service-mcp:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: reputation-service-mcp
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/reputation-service-mcp" ]
    environment:
      - API_KEY=37a69dbb-093a-4152-9444-5b1c6ecf44f4
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3007"
    ports:
      - "7307:3007"
    restart: unless-stopped

  harmony-sase-mcp:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: harmony-sase-mcp
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/harmony-sase-mcp" ]
    environment:
      - API_KEY=
      - MANAGEMENT_HOST=
      - REGION=
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3008"
    ports:
      - "7308:3008"
    restart: unless-stopped

  quantum-gw-cli-mcp:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: quantum-gw-cli-mcp
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/quantum-gw-cli-mcp" ]
    environment:
      - MANAGEMENT_HOST=
      - API_KEY=
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3009"
    ports:
      - "7309:3009"
    restart: unless-stopped

  quantum-gw-connection-analysis-mcp:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: quantum-gw-connection-analysis-mcp
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/quantum-gw-connection-analysis-mcp" ]
    environment:
      - MANAGEMENT_HOST=
      - API_KEY=
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3010"
    ports:
      - "7310:3010"
    restart: unless-stopped

  quantum-gaia-mcp:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: quantum-gaia-mcp
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/quantum-gaia-mcp" ]
    environment:
      - MANAGEMENT_HOST=
      - API_KEY=
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3011"
    ports:
      - "7311:3011"
    restart: unless-stopped

  cpinfo-analysis-mcp:
    env_file:
      - .env
    image: custom-mcp-n8n:custom
    container_name: cpinfo-analysis-mcp
    networks: [ "demo" ]
    depends_on:
      - n8n
    entrypoint: [ "/usr/local/bin/cpinfo-analysis-mcp" ]
    environment:
      - MANAGEMENT_HOST=
      - API_KEY=
      - LOG_LEVEL=info
    command:
      - "--transport"
      - "http"
      - "--transport-port"
      - "3012"
    ports:
      - "7312:3012"
    volumes:
      - /etc/dokploy/compose/cp-agentic-mcp-playground-ataahy/code/n8n/shared:/data/cpinfo
    restart: unless-stopped